# Generated by Django 6.1.1 on 2026-10-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=200)),
                ('person_title', models.CharField(blank=True, help_text='Role/company, if known — improves reply quality.', max_length=200)),
                ('text', models.TextField()),
                ('reply', models.TextField(blank=True)),
                ('reply_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
