# Generated by Django 6.1.1 on 2026-10-05 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_extra_avatar_item_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('base', 'Base'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkspaceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='brand.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'period_start')},
            },
        ),
        migrations.DeleteModel(
            name='UsageCounter',
        ),
    ]
