# Generated by Django 5.2.17 on 2026-10-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_stripe_extra_avatar_item_id_and_more'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_events', to='brand.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='billing_aiu_created_68c57c_idx'), models.Index(fields=['purpose'], name='billing_aiu_purpose_568cdc_idx'), models.Index(fields=['model'], name='billing_aiu_model_4ce972_idx')],
            },
        ),
    ]
