# Generated by Django 5.2.17 on 2026-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_aiusageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('free', 'Free'), ('base', 'Base'), ('pro', 'Pro')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('price_monthly_inr', models.PositiveIntegerField(default=0)),
                ('included_workspaces', models.PositiveSmallIntegerField(default=1)),
                ('max_workspaces', models.PositiveSmallIntegerField(default=1)),
                ('extra_workspace_price_inr', models.PositiveIntegerField(blank=True, help_text='Blank = no additional avatars allowed on this plan.', null=True)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('ai_budget_usd_per_workspace', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('stripe_extra_avatar_price_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
