# Generated by Django 5.2.17 on 2026-10-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_planconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('ai', 'AI-powered'), ('non_ai', 'Non-AI')], default='ai', max_length=10)),
                ('value_kind', models.CharField(choices=[('boolean', 'On / off'), ('quantity', 'Quantity per month'), ('tier', 'Quality tier')], default='boolean', max_length=10)),
                ('unit', models.CharField(blank=True, help_text="e.g. 'posts/month', 'replies/month' — shown next to the quantity.", max_length=40)),
                ('tier_options', models.JSONField(blank=True, default=list, help_text='For \'tier\' kind: the allowed values, e.g. ["none","1_month","3_months"].')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='planconfig',
            name='ai_enabled',
        ),
        migrations.AddField(
            model_name='planconfig',
            name='is_default_free',
            field=models.BooleanField(default=False, help_text='Canceled/downgraded subscriptions fall back to whichever plan has this set. Exactly one plan should have it.'),
        ),
        migrations.AlterField(
            model_name='planconfig',
            name='ai_budget_usd_per_workspace',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Safety cap on AI $ spend per avatar/month, on top of the per-feature quotas below.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='planconfig',
            name='key',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='free', max_length=40),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text="Used when the feature's value kind is 'quantity'.", null=True)),
                ('tier', models.CharField(blank=True, help_text="Used when the feature's value kind is 'tier'.", max_length=40)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='billing.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='billing.planconfig')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
