# Generated by Django 6.1.1 on 2026-10-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('brief', models.TextField(blank=True)),
                ('num_posts', models.PositiveSmallIntegerField(default=4)),
                ('num_articles', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_plans', to='brand.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('angle', models.TextField(blank=True, help_text='The hook/angle Claude proposed for this title.')),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('article', 'Article')], default='post', max_length=10)),
                ('suggested_date', models.DateField()),
                ('date_rationale', models.CharField(blank=True, help_text='Why this date — e.g. "Tuesday, high-engagement day".', max_length=300)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.contentplan')),
            ],
            options={
                'ordering': ['order', 'suggested_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post', 'Post'), ('article', 'Article')], default='post', max_length=10)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending your approval'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0, help_text="Impressions, self-reported from LinkedIn's post analytics.")),
                ('predicted_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('predicted_reason', models.TextField(blank=True)),
                ('predicted_tip', models.TextField(blank=True)),
                ('next_step_suggestion', models.TextField(blank=True)),
                ('next_step_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.contentplan')),
                ('planned_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='content.planneditem')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='brand.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('prompt', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('generated', 'AI generated'), ('uploaded', 'Uploaded')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.post')),
            ],
        ),
    ]
