# Generated by Django 6.1.1 on 2026-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='Overrides ANTHROPIC_API_KEY in .env when set. Leave blank to use the .env value.', max_length=200)),
                ('openai_api_key', models.CharField(blank=True, help_text='Overrides OPENAI_API_KEY in .env when set. Leave blank to use the .env value.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider settings',
                'verbose_name_plural': 'AI provider settings',
            },
        ),
    ]
