# Generated by Django 5.2.17 on 2026-10-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='default_claude_model',
            field=models.CharField(blank=True, help_text='Overrides CLAUDE_MODEL in .env when set.', max_length=80),
        ),
    ]
