export const metadata = { title: "Terms of Service — Postroom" };

export default function TermsPage() {
  return (
    <main className="page" style={{ maxWidth: 720 }}>
      <div className="card" style={{ borderColor: "var(--signal)", background: "var(--accent-soft)" }}>
        <p style={{ margin: 0, fontSize: "0.85rem" }}>
          <strong>Template — not legal advice.</strong> Replace the bracketed items and have a
          lawyer review this before launch, especially the sections on AI-generated content,
          data processing, and liability.
        </p>
      </div>

      <h1>Terms of Service</h1>
      <p className="hint">Last updated: [date]</p>

      <h2 className="section-title">1. What Postroom is</h2>
      <p>Postroom ("we", "us") provides a platform to help you plan, write, schedule, and track
        LinkedIn content, using third-party AI providers (Anthropic and OpenAI) to generate drafts,
        images, and suggestions. You remain responsible for everything you publish.</p>

      <h2 className="section-title">2. Your account</h2>
      <p>You must provide accurate information when registering and are responsible for activity
        under your account. Tell us immediately if you believe your account has been compromised.</p>

      <h2 className="section-title">3. AI-generated content</h2>
      <p>Drafts, images, and suggestions are generated by third-party AI models and may contain
        errors, inaccuracies, or placeholder text (e.g. "[ADD DETAIL]") that you must review and
        edit before publishing. We do not guarantee the accuracy, originality, or suitability of
        AI-generated content. You are solely responsible for what you post to LinkedIn or elsewhere.</p>

      <h2 className="section-title">4. Subscriptions and billing</h2>
      <p>Paid plans are billed monthly in advance via Stripe. You can cancel anytime from the
        Billing page; your plan remains active until the end of the current billing period. We
        don't offer refunds for partial months except where required by law.</p>

      <h2 className="section-title">5. Acceptable use</h2>
      <p>Don't use Postroom to generate content that is illegal, infringing, harassing, or violates
        LinkedIn's own Terms of Service or Platform Policies. We may suspend accounts that misuse
        the service, including excessive automated use that abuses shared AI provider capacity.</p>

      <h2 className="section-title">6. Third-party services</h2>
      <p>Postroom integrates with Anthropic (Claude), OpenAI, and (where you connect it) LinkedIn's
        own API. Your use of those integrations is also subject to those providers' own terms.</p>

      <h2 className="section-title">7. Disclaimers and liability</h2>
      <p>The service is provided "as is." To the maximum extent permitted by law, we aren't liable
        for indirect, incidental, or consequential damages, including reputational harm from
        content you chose to publish.</p>

      <h2 className="section-title">8. Changes</h2>
      <p>We may update these terms and will post the new version here with an updated date.
        Continued use after changes means you accept the new terms.</p>

      <h2 className="section-title">9. Contact</h2>
      <p>Questions about these terms: [support email].</p>
    </main>
  );
}
