# Generated by Django 6.1.1 on 2026-10-04 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Alex (founder)' or 'Northwind — company page'", max_length=150)),
                ('persona_type', models.CharField(choices=[('individual', 'Myself'), ('company', 'Company spokesperson')], default='individual', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reference_images/')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='brand.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PastPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('posted_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_posts', to='brand.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('metric', models.CharField(choices=[('likes', 'Likes'), ('comments', 'Comments'), ('posts', 'Posts published')], default='likes', max_length=20)),
                ('target_value', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('week', 'This week'), ('month', 'This month'), ('quarter', 'This quarter'), ('custom', 'Custom range')], default='month', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='brand.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_website', models.URLField(blank=True)),
                ('website_summary', models.TextField(blank=True, help_text="Claude's summary of the company site, used as writing context.")),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('target_audience', models.TextField(blank=True)),
                ('core_topics', models.CharField(blank=True, help_text='Comma-separated topics.', max_length=500)),
                ('voice_notes', models.TextField(blank=True, help_text='Manual notes: words to avoid, things never to post about, etc.')),
                ('tone_summary', models.TextField(blank=True)),
                ('tone_traits', models.JSONField(blank=True, default=list)),
                ('tone_language', models.TextField(blank=True)),
                ('tone_sample_post', models.TextField(blank=True, help_text='A short sample Claude wrote in this tone, shown with a disclaimer.')),
                ('tone_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('tone_posts_analyzed', models.PositiveIntegerField(default=0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='brand.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='brand.workspace')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('workspace', 'date')},
            },
        ),
    ]
